site_name: 查表法量化激活函数
site_url: https://yehangyang.github.io/Table_Based_Quantization/

repo_url: https://github.com/yehangyang/Table_Based_Quantization
repo_name: Table_Based_Quantization
edit_uri: edit/main/docs/

theme:
    name: material
    palette:
        - scheme: default
          primary: indigo
          accent: indigo
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        - scheme: slate
          primary: indigo
          accent: indigo
          toggle:
              icon: material/weather-night
              name: Switch to light mode

    font:
        text: Roboto
        code: Roboto Mono

    features:
        - navigation.tabs
        - content.code.copy
        - content.code.select
        - content.code.annotate
        - content.action.edit

    icon:
        edit: material/pencil
        view: material/eye
        repo: fontawesome/brands/github

    custom_dir: overrides

markdown_extensions:
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
    - git-revision-date-localized:
          enable_creation_date: true

# Page Tree
nav:
    - 主页: index.md
    - 介绍:
        - 术语介绍: introduce_term.md
        - 方法介绍: introduce_method.md
        - 查表法量化 Softmax: introduce_softmax.md
        - 查表法量化 TanH: introduce_tanh.md
